repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=119
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.11.2'
    hooks:
      - id: ruff
        args:
          - --fix
          - --ignore=E402
          - --exit-non-zero-on-fix
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       args:
  #         - --profile=black
  #         - --skip-glob=wandb/**/*
  #         - --thirdparty=wandb
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - -w
          - --ignore-words-list=nd,reacher,ths,magent,ba,fo,doesnt,dout
